services:
  practice_pg:
    container_name: practice_pg
    image: postgres:latest
    restart: always
    env_file:
      - docker.env
    ports:
      - '5434:5432'

  practice_redis:
    container_name: practice_redis
    image: redis:alpine
    env_file:
      - docker.env
    ports:
      - '6380:6379'

  practice_minio:
    image: docker.io/bitnami/minio:2022
    env_file:
      - docker.env
    ports:
      - "9000:9000"
      - "9002:9002"
    platform: linux/amd64

